# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(261, 301)
        Form.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"}\n"
"QWidget:hover {\n"
"    border: 2px solid #007bff;\n"
"    box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n"
"}")
        self.line_top = QtWidgets.QFrame(parent=Form)
        self.line_top.setGeometry(QtCore.QRect(10, 0, 241, 20))
        self.line_top.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_top.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_top.setObjectName("line_top")
        self.line_left = QtWidgets.QFrame(parent=Form)
        self.line_left.setGeometry(QtCore.QRect(0, 10, 16, 281))
        self.line_left.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_left.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_left.setObjectName("line_left")
        self.line_bottom = QtWidgets.QFrame(parent=Form)
        self.line_bottom.setGeometry(QtCore.QRect(10, 280, 241, 20))
        self.line_bottom.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_bottom.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_bottom.setObjectName("line_bottom")
        self.line_right = QtWidgets.QFrame(parent=Form)
        self.line_right.setGeometry(QtCore.QRect(240, 10, 16, 281))
        self.line_right.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_right.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_right.setObjectName("line_right")
        self.lbl_product_name = QtWidgets.QLabel(parent=Form)
        self.lbl_product_name.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.lbl_product_name.setObjectName("lbl_product_name")
        self.lbl_product_image = QtWidgets.QLabel(parent=Form)
        self.lbl_product_image.setGeometry(QtCore.QRect(30, 40, 201, 161))
        self.lbl_product_image.setText("")
        self.lbl_product_image.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/../Img/how-to-donate-computer-1-500x500.webp"))
        self.lbl_product_image.setScaledContents(True)
        self.lbl_product_image.setObjectName("lbl_product_image")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 260, 231, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_add_to_cart = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_add_to_cart.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"}")
        self.btn_add_to_cart.setObjectName("btn_add_to_cart")
        self.gridLayout_2.addWidget(self.btn_add_to_cart, 0, 0, 1, 1)
        self.btn_buy_now = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_buy_now.setStyleSheet("QPushButton {\n"
"    background-color: #dc3545;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"}")
        self.btn_buy_now.setObjectName("btn_buy_now")
        self.gridLayout_2.addWidget(self.btn_buy_now, 0, 1, 1, 1)
        self.btn_view_detail = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_view_detail.setStyleSheet("QPushButton {\n"
"    background-color: #007bff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"    font-size: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0056b3;\n"
"}")
        self.btn_view_detail.setObjectName("btn_view_detail")
        self.gridLayout_2.addWidget(self.btn_view_detail, 1, 0, 1, 2)
        self.lbl_rating = QtWidgets.QLabel(parent=Form)
        self.lbl_rating.setGeometry(QtCore.QRect(180, 200, 49, 16))
        self.lbl_rating.setObjectName("lbl_rating")
        self.lbl_star_icon = QtWidgets.QLabel(parent=Form)
        self.lbl_star_icon.setGeometry(QtCore.QRect(130, 180, 51, 41))
        self.lbl_star_icon.setText("")
        self.lbl_star_icon.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/../Img/star.png"))
        self.lbl_star_icon.setScaledContents(True)
        self.lbl_star_icon.setObjectName("lbl_star_icon")
        self.lbl_price = QtWidgets.QLabel(parent=Form)
        self.lbl_price.setGeometry(QtCore.QRect(20, 230, 211, 21))
        self.lbl_price.setStyleSheet("font: 700 19pt \"Segoe UI\";")
        self.lbl_price.setObjectName("lbl_price")
        self.line_top.raise_()
        self.line_left.raise_()
        self.line_right.raise_()
        self.line_bottom.raise_()
        self.lbl_product_name.raise_()
        self.lbl_product_image.raise_()
        self.gridLayoutWidget.raise_()
        self.lbl_rating.raise_()
        self.lbl_star_icon.raise_()
        self.lbl_price.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_product_name.setText(_translate("Form", "Intel CORE i5 32GB Ram DELL Desktop C..."))
        self.btn_add_to_cart.setText(_translate("Form", "Add to Cart"))
        self.btn_buy_now.setText(_translate("Form", "Buy Now"))
        self.btn_view_detail.setText(_translate("Form", "View Detail"))
        self.lbl_rating.setText(_translate("Form", "4.6"))
        self.lbl_price.setText(_translate("Form", "999.999.999 VND"))
