# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 800)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 961, 801))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/../Img/laptops-modern-electronics-store-computer-department-technology-140964701.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(260, 70, 481, 491))
        self.label_2.setStyleSheet("background-color: rgba(50, 50, 50, 200); /* Dark gray with transparency */\n"
"border-radius: 20px;                    /* Curved edges */\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/Img/blank..png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(370, 90, 261, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/../Img/Logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(430, 150, 221, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(330, 270, 311, 41))
        self.txt_email.setStyleSheet("border-radius: 10px;\n"
"")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(330, 350, 311, 41))
        self.txt_password.setStyleSheet("border-radius: 10px;\n"
"")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(330, 240, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("Color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(330, 320, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("Color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.btn_sign_up = QtWidgets.QPushButton(parent=Form)
        self.btn_sign_up.setGeometry(QtCore.QRect(490, 490, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.btn_sign_up.setFont(font)
        self.btn_sign_up.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius: 10px;\n"
"")
        self.btn_sign_up.setObjectName("btn_sign_up")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(330, 500, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("Color:rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(330, 420, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius: 10px;\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.btn_eye = QtWidgets.QPushButton(parent=Form)
        self.btn_eye.setGeometry(QtCore.QRect(590, 350, 41, 41))
        self.btn_eye.setStyleSheet("background:none;")
        self.btn_eye.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/BaoKhang/python-app/ui/../Img/eye-slash-regular.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye.setIcon(icon)
        self.btn_eye.setIconSize(QtCore.QSize(32, 32))
        self.btn_eye.setObjectName("btn_eye")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Log On"))
        self.txt_email.setPlaceholderText(_translate("Form", "Enter Username Here"))
        self.txt_password.setPlaceholderText(_translate("Form", "Enter Password Here"))
        self.label_5.setText(_translate("Form", "Email"))
        self.label_7.setText(_translate("Form", "Enter Password"))
        self.btn_sign_up.setText(_translate("Form", "Sign Up"))
        self.label_11.setText(_translate("Form", "Dont have a account?"))
        self.btn_login.setText(_translate("Form", "Log In"))
